# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
#
# SPDX-License-Identifier: Unlicense
name: Release Actions

on:
  release:
    types: [published]

jobs:
  upload-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check For setup.py
      id: need-pypi
      run: |
        echo "setup-py=$( find . -wholename './setup.py' )" >> $GITHUB_OUTPUT
    - name: Set up Python
      if: contains(steps.need-pypi.outputs.setup-py, 'setup.py')
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      if: contains(steps.need-pypi.outputs.setup-py, 'setup.py')
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build twine
    - name: Build and publish
      if: contains(steps.need-pypi.outputs.setup-py, 'setup.py')
      env:
        TWINE_USERNAME: ${{ secrets.pypi_username }}
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        for file in $(find -not -path "./.*" -not -path "./docs*" \( -name "*.py" -o -name "*.toml" \) ); do
            sed -i -e "s/0.0.0+auto.0/${{github.event.release.tag_name}}/" $file;
        done;
        python -m build
        twine upload dist/*
